version: '3.8'


services: 
    web:
        build: .
        # command: python /code/manage.py runserver 0.0.0.0:8000
        command: gunicorn bookstore_project.wsgi -b 0.0.0.0:8000
        volumes:
            - .:/code
        environment: 
            - ENVIRONMENT=production
            - SECRET_KEY=django-insecure-+58@x2mb-5nt49xcx(8623v@=7x+-gx3za!^4t+(n4he)1cf3#
            - DEBUG=0
            - STRIPE_TEST_PUBLISHABLE_KEY=pk_test_51IiL2tSAwb2vRd35LYQAp1k3a5HevPcooSi3oTDUn4A3paZVh5M7ZptHPN9nBZrFfwXnrFqNQ36WTl0JR0GpgfEL00XvDFZUO3
            - STRIPE_TEST_SECRET_KEY=sk_test_51IiL2tSAwb2vRd35WdGdcPFf9Caf5s7pxlfpxjV9UizHOvMYIFrTJhkOqXIvdI1N4nAJ5H1UnCrQPvrcQFimUTvZ00Z2FA0lgN
        ports:
            - 8000:8000
        depends_on: 
            - db
    db:
        image: postgres:11
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
    postgres_data: