version: '3.8'


services: 
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8000
        environment: 
            - SECRET_KEY=django-insecure-+58@x2mb-5nt49xcx(8623v@=7x+-gx3za!^4t+(n4he)1cf3#
            - DEBUG=1
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on: 
            - db
    db:
        image: postgres:11
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment: 
            - "POSTGRES_HOST_AUTH_METHOD=trust"


volumes:
    postgres_data: